server:
  port: 5000

spring:
  influxdb2:
    url: "http://101.132.32.165:8086"
    token: "tgk01RkCJAhklRaAKbbl3zdGKclUfegdwFK27VsFQ-lGz8pESN7Bt5pLl1CFqIzqYq8TL3b-wgoqlG7WxMWjHA=="
    org: "NUAA"
    bucket: "MQTT"

allowed:
   origin: http://101.132.32.165 # prod
#  origin: http://localhost:9527 # dev
